import { Inter } from 'next/font/google'
import Topbar from './components/Topbar'
import AuthContext from './components/AuthContext'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Delta Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
        <Topbar/>
        {children}
        <ToastContainer/>
        </AuthContext>
        </body>
    </html>
  )
}
